config/routes.rb
RorTeam::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'

  resources :posts, path: 'news', only: [:index] do
    resources :comments, only: [:new, :create]
  end
  resources :home, only: [:index, :create]
  resources :team, only: [:index, :show]
  resources :company, only: [:index]
  resources :projects, only: [:index]
  resources :jobs, only: [:index, :show, :create]
  resources :contact, only: [:index, :create]
  resources :resume, only: [:new, :create, :show]

  get 'news/:created/:id' => 'posts#show', as: :special_post
  get 'news/archives/:month/:year' => 'posts#archives', as: :archives
  post '/news/comments' => 'comments#create'

  post '/admin/time_online' => 'time_onlines#set_time'
  post '/comment_load' => 'posts#comments_show_all'

  #=============================================== User chat =================
  post 'chat/new' => 'live_chats#new'
  post 'chat/create' => 'live_chats#create', as: :user_chat_create
  post 'chat/close' => 'live_chats#close'
  post 'chat/send' => 'live_chats#msg_send', as: :user_chat
  #=============================================== Admin chat ================
  post '/pusher/auth'
  post '/admin_chat/send_msg'
  post '/admin_chat/close'
  post '/admin_chat/go_offline', as: :admin_go_offline
  #===========================================================================

  get 'projects/:id' => 'projects#show', as: :project_load

  root to: 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :last_posts_and_jobs , only: :index

  def index
    @message = Message.new
    @projects = Project.includes(:upload_files).order('random()').limit(8)
    @testimonials = ClientTestimonial.order('random()').limit(6)
    @team = TeamMember.includes(:team_role)
    @team_roles = TeamRole.all
    @advantages = Advantage.order('created_at DESC').limit(5)
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, notice: t('.contact_sent_msg'))
    else
      flash.now[:error] = @message.errors.full_messages.join(', ')
      redirect_to :back
    end
  end

end

app/views/home/_contact_section.html.haml
%section#Contacts.Contacts_l-1
  .Contacts_l-3
  .content_area
    .row{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-120-top" => "opacity:0.1;transform: scale(0.9)"}
      %h2= t 'home.index.contact_us'
    .contact_form
      = form_for @message, url: home_index_path, html: {class: 'web-form', multipart: true} do |form|
        - if @message.errors.any?
          .ror-team-errors
            %h6
              = pluralize(@message.errors.count, 'error')
              prohibited this message from being sent:
            %ul
              - @message.errors.full_messages.each do |msg|
                %li= msg
        %h4 We will respond as soon as we can
        .clearfix
          .left_side
            = form.label :name do
              Name
              = form.text_field(:name, required: "")
            = form.label :email do
              Email
              = form.email_field(:email, required: "")
          .right_side
            = form.label :text do
              Message
              = form.text_area(:text, required: "")
        = submit_tag 'Submit'
      .copyRight
        = cache 'contact_description' do
          %p
        %span
          = "sbs-team #{Time.now.strftime('%Y')}"

app/views/home/_portfolio_section.html.haml
%section#Portfolio.Portfolio_l-1
  .Portfolio_l-2{"data-0" => "background-position:50% -1000px;", "data-100000" => "background-position:50% 40000px;"}
  .content_area
    .row{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-120-top" => "opacity:0.1;transform: scale(0.9)"}
      %h2= t 'home.index.project_work'
    .portfolio_item_list
      - @projects.each do |project|
        = cache project do
          .portfolio_item
            = link_to project_load_path(project.id), class: 'img_block manual-ajax', rel: 'modal:open' do
              %span.bg_place_holder
              %span.bg_place_holder_plus
              - unless project.upload_files.blank?
                = image_tag(project.upload_files.sample.img_name.url(:thumb), width: 167, height: 110)
              - else
                = image_tag('no_image.gif')
            = link_to project.url, project.url, target: '_blank', class: 'site_link'

app/views/home/_team_section.html.haml
= cache 'team-section' do
  %section#team.team-section
    .team-section-wrapper
      .content_area
        .row{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-120-top" => "opacity:0.1;transform: scale(0.9)"}
          %h2 Ruby Team
      .team-photo-wrapper
        .team-section-left
          .team-role-filter
            %ul
              %li
                = link_to 'Full team', '#', class: 'filter-link active-role', 'data-role' => 'all'
              - @team_roles.each do |role|
                %li
                  = link_to role.name, '#', class: 'filter-link', 'data-role' => role.name.downcase
        .team-section-content
          - @team.each do |member|
            = cache member do
              .team-item{'data-team-role' => member.team_role.name.downcase}
                = image_tag member.image_url(:thumb), width: 100, height: 100
                .team-item-content
                  %span= member.name.capitalize
                  %span= member.last_name.capitalize
                  %div= member.team_role.name
    %h2.row.job_interest{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-80-top" => "opacity:0.1;transform: scale(0.9)"}
      Want to join
      %br
      the Ruby Team?
    = link_to 'Click here to apply!', new_resume_path, class: 'send_resume', rel: 'modal:open'

app/views/home/_welcome_section.html.haml
= cache "welcome_section" do
  %section#welcome.welcome_l-1
    .welcome_l-2{"data-0" => "background-position:0px 0px;", "data-100000" => "background-position:0px 50000px;"}
    .welcome_l-3{"data-0" => "background-position:0px 0px;", "data-100000" => "background-position:0px 10000px;"}
    .content_area
      %h1 welcome
      %h3 to
      .circle
        = image_tag 'sbs_c.png'

app/views/home/_what_we_do_section.html.haml
= cache 'what_we_do' do
  %section#What_we_do
    .content_area
      .row{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-120-top" => "opacity:0.1;transform: scale(0.9)"}
        %h2= t 'home.index.our_command'
      .row{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-120-top" => "opacity:0.1;transform: scale(0.9)"}
        %p
          %span.font_size-39> We're young and energetic team
          %span.font_size-26
            = " within a web development company"
      .row{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-120-top" => "opacity:0.1;transform: scale(0.9)"}
        %p
          of any complexity
          %span.font_size-51 delivering web development services
      .row{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-120-top" => "opacity:0.1;transform: scale(0.9)"}
        %p
          to clients
          %span.font_size-61  worldwide.
          We strive to use
      .row{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-120-top" => "opacity:0.1;transform: scale(0.9)"}
        %p the latest technologies
      .row{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-120-top" => "opacity:0.1;transform: scale(0.9)"}
        %p
          in the area of web development,
          %span.font_size-32 and produce clean and robust code.
          %span.font_size-52 Our team develops
      .row{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-120-top" => "opacity:0.1;transform: scale(0.9)"}
        %p
          %span.font_size-70> projects using mainly the Ruby-on-Rails Framework.
          = " Being a rather young team,"
      .row{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-120-top" => "opacity:0.1;transform: scale(0.9)"}
        %p
          we're flexible and
          %span.font_size-39 and always search a best possible solution
      .row{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-120-top" => "opacity:0.1;transform: scale(0.9)"}
        %p
          for each project we work.
          %span.font_size-48 Our goal
          is to make
      .row{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-120-top" => "opacity:0.1;transform: scale(0.9)"}
        %p
          our clients
          %span.font_size-59 happy
      .row{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-120-top" => "opacity:0.1;transform: scale(0.9)"}
        %p
          %span.font_size-39> with a
          = " high quality"
          %span.font_size-26 product.

app/views/home/_why_sbs.html.haml
%section#why_sbs.why_sbs
  .content_area
    .row{"data--50-bottom" => "opacity:0.1;transform: scale(0.9)", "data-120-top" => "opacity:0.1;transform: scale(0.9)"}
      %h2 Why choose SBS
  .all_advantages
    - @advantages.each do |adv|
      = cache adv do
        .advantage
          .adv_img
            = image_tag adv.image_url(:thumb)
          .adv.descr
            = adv.description
  -#.client_testimonials_block
  -#  %h3 Client Testimonials
  -#  .testimonials
  -#    - @testimonials.each do |testimonial|
  -#      = cache testimonial do
  -#        .testimonial
  -#          .testimonial_title
  -#            = testimonial.author_position.capitalize unless testimonial.author_position.blank?
  -#            = testimonial.author_name.titleize
  -#            %span.project
  -#              = "(#{testimonial.project.name})"
  -#          .testimonial_text
  -#            = testimonial.comment_text

app/views/home/index.html.haml
= render partial: 'welcome_section'
= render partial: 'what_we_do_section'
= render partial: 'why_sbs'
= render partial: 'portfolio_section'
= render partial: 'team_section'
= render partial: 'contact_section'