config/routes.rb
RorTeam::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'

  resources :posts, path: 'news', only: [:index] do
    resources :comments, only: [:new, :create]
  end
  resources :home, only: [:index, :create]
  resources :team, only: [:index, :show]
  resources :company, only: [:index]
  resources :projects, only: [:index]
  resources :jobs, only: [:index, :show, :create]
  resources :contact, only: [:index, :create]
  resources :resume, only: [:new, :create, :show]

  get 'news/:created/:id' => 'posts#show', as: :special_post
  get 'news/archives/:month/:year' => 'posts#archives', as: :archives
  post '/news/comments' => 'comments#create'

  post '/admin/time_online' => 'time_onlines#set_time'
  post '/comment_load' => 'posts#comments_show_all'

  #=============================================== User chat =================
  post 'chat/new' => 'live_chats#new'
  post 'chat/create' => 'live_chats#create', as: :user_chat_create
  post 'chat/close' => 'live_chats#close'
  post 'chat/send' => 'live_chats#msg_send', as: :user_chat
  #=============================================== Admin chat ================
  post '/pusher/auth'
  post '/admin_chat/send_msg'
  post '/admin_chat/close'
  post '/admin_chat/go_offline', as: :admin_go_offline
  #===========================================================================

  get 'projects/:id' => 'projects#show', as: :project_load

  root to: 'home#index'

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  since       :date
#  team_size   :integer
#  created_at  :datetime
#  updated_at  :datetime
#  till        :date
#  url         :string(255)
#

class Project < ActiveRecord::Base

  has_many :project_services, dependent: :destroy
  has_many :services, through: :project_services
  has_many :project_technology_categories, dependent: :destroy
  has_many :technologies, through: :project_technology_categories
  has_many :upload_files, as: :fileable, dependent: :destroy
  has_many :client_testimonials, dependent: :destroy

  accepts_nested_attributes_for :upload_files
  accepts_nested_attributes_for :project_technology_categories, allow_destroy: true

  validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 45}
  validates :description, presence: true, length: {in: 10..5000}
  validates :since, presence: true
  validates :team_size, presence: true, numericality: {only_integer: true, greater_than: 0}
  validates :upload_files, presence: true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :last_posts_and_jobs , only: [:index, :show]

  def index
    @projects = Project.includes([{technologies: :technology_category}, :services, :project_services,
                                  :upload_files]).order('created_at DESC').page(params[:page]).per(2)
  end

  def show
    @project = Project.includes(:upload_files, technologies: :upload_file).find(params[:id])
    respond_to do |format|
      format.html {render :show, layout: false}
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def technologies_inject(project)
    project.technologies.inject({}) {|res, elem| res[elem.technology_category.name] ||= []; res[elem.technology_category.name].push(elem); res}
  end

end

app/views/projects/index.html.haml
- @projects.each do |project|
  - image_amount = project.upload_files.count
  .col-lg-12
    %h2
      = project.name
  .col-lg-12.project_item
    .col-lg-6
      - unless project.upload_files.blank? || project.upload_files.first.img_name.blank?
        .carousel.slide{id: "myCarousel#{project.id}"}
          - if image_amount > 1
            %ol.carousel-indicators
              - image_amount.times do |i|
                %li{'data-slide-to' => "#{i}", 'data-target' => "#myCarousel#{project.id}", class: "#{'active' if i == 0}"}
          .carousel-inner
            - project.upload_files.each do |file|
              - if file.img_name == project.upload_files.first.img_name
                .item.active
                  = image_tag file.img_name.url
              - else
                .item
                  = image_tag file.img_name.url
          - if project.upload_files.count > 1
            = link_to "#myCarousel#{project.id}", 'data-slide' => 'prev', class: 'carousel-control left' do
              %span.icon-prev
            = link_to "#myCarousel#{project.id}", 'data-slide' => 'next', class: 'carousel-control right' do
              %span.icon-next
      .text.project-descr
        != project.description
    .col-lg-6
      .project-name-url.row
        .project-name.col-lg-6
          = link_to project.name, project_path(project), class: 'btn btn-primary btn-small'
        - unless project.url.blank?
          .project-url.col-lg-6
            = link_to project.url, "#{project.url}", class: 'btn btn-success btn-small', target: '_blank'
      .project-terms.row
        .col-lg-6
          %p
            %b
              = t '.since'
            = project.since
        .col-lg-6
          %p
            %b
              = t '.team_size'
            = pluralize(project.team_size.to_i, t('.people'))
        .col-lg-12
          %p
            %b
              = t '.till'
            = project.till ? project.till.strftime('%Y-%m-%d') : t('.in_work')
      .team-info.row
        - project.services.each do |service|
          .developer-info.text-center.col-lg-3
            .photo
              - unless service.upload_file.blank? || service.upload_file.img_name.blank?
                = link_to(company_index_path) do
                  = image_tag(service.upload_file.img_name.to_s, class: 'img-polaroid', height: 100)
              - else
                = image_tag 'no_image.gif', height: 120
            = link_to "#{service.name}", company_index_path
      - unless project.technologies.blank?
        .tech-info
          %h4
            = t '.tech_info'
          %dl.dl-horizontal
            - grouped_categories = technologies_inject(project)
            - grouped_categories.each do |category, technologies|
              %dt
                = category
              - technologies.each do |technology|
                %dd
                  = technology
.col-lg-12
  = paginate @projects
.row
  = render partial: 'shared/post_jobs'

app/views/projects/show.html.haml
.portfolio_item_content
  .left_side
    - @project.upload_files.each do |file|
      = image_tag file.img_name.url, alt: ''
  .right_side
    = link_to 'back', '#', class: 'backButton', rel: 'modal:close'
    %h1= @project.name
    %p!= @project.description
    .portfolio_item_technologi_wrapper
      %h4= t '.tech_info'
      - unless @project.technologies.blank?
        %ul.portfolio_item_technologi_list
          - @project.technologies.each do |tech|
            %li
              = image_tag tech.upload_file.img_name, alt: ''
              %p= tech.description
    = link_to 'back', '#', class: 'backButton', rel: 'modal:close'


-#- image_amount = @project.upload_files.count
-#.col-lg-12
-#  %h1
-#    = @project.name
-#.col-lg-12.project_item
-#  .col-lg-6
-#    - unless @project.upload_files.blank? || @project.upload_files.first.img_name.blank?
-#      .carousel.slide{id: "myCarousel#{@project.id}"}
-#        - if image_amount > 1
-#          %ol.carousel-indicators
-#            - image_amount.times do |i|
-#              %li{'data-slide-to' => "#{i}", 'data-target' => "#myCarousel#{@project.id}", class: "#{'active' if i == 0}"}
-#        .carousel-inner
-#          - @project.upload_files.each do |file|
-#            - if file.img_name == @project.upload_files.first.img_name
-#              .item.active
-#                = image_tag file.img_name.url
-#            - else
-#              .item
-#                = image_tag file.img_name.url
-#        - if @project.upload_files.count > 1
-#          = link_to "#myCarousel#{@project.id}", 'data-slide' => 'prev', class: 'carousel-control left' do
-#            %span.icon-prev
-#          = link_to "#myCarousel#{@project.id}", 'data-slide' => 'next', class: 'carousel-control right' do
-#            %span.icon-next
-#    .text.project-descr
-#      != @project.description
-#  .col-lg-6
-#    .project-name-url.row
-#      .project-name.col-lg-6
-#        %span.btn.btn-primary.btn-small
-#          = @project.name
-#      - unless @project.url.blank?
-#        .project-url.col-lg-6
-#          = link_to @project.url, "#{@project.url}", class: 'btn btn-success btn-small', target: '_blank'
-#    .project-terms.row
-#      .col-lg-6
-#        %p
-#          %b
-#            = t '.since'
-#          = @project.since
-#      .col-lg-6
-#        %p
-#          %b
-#            = t '.team_size'
-#          = pluralize(@project.team_size.to_i, t('.people'))
-#      .col-lg-12
-#        %p
-#          %b
-#            = t '.till'
-#          = @project.till ? @project.till.strftime('%Y-%m-%d') : t('.in_work')
-#    .team-info.row
-#      - @project.services.each do |service|
-#        .developer-info.text-center.col-lg-3
-#          .photo
-#            - unless service.upload_file.blank? || service.upload_file.img_name.blank?
-#              = link_to(company_index_path) do
-#                = image_tag(service.upload_file.img_name.to_s, class: 'img-polaroid', height: 100)
-#            - else
-#              = image_tag 'no_image.gif', height: 100
-#          = link_to "#{service.name}", company_index_path
-#    - unless @project.technologies.blank?
-#      .tech-info
-#        %h4
-#          = t '.tech_info'
-#        %dl.dl-horizontal
-#          - grouped_categories = technologies_inject(@project)
-#          - grouped_categories.each do |category, technologies|
-#            %dt
-#              = category
-#            - technologies.each do |technology|
-#              %dd
-#                = technology
-#.row
-#  = render partial: 'shared/post_jobs'