config/routes.rb
RorTeam::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'

  resources :posts, path: 'news', only: [:index] do
    resources :comments, only: [:new, :create]
  end
  resources :home, only: [:index, :create]
  resources :team, only: [:index, :show]
  resources :company, only: [:index]
  resources :projects, only: [:index]
  resources :jobs, only: [:index, :show, :create]
  resources :contact, only: [:index, :create]
  resources :resume, only: [:new, :create, :show]

  get 'news/:created/:id' => 'posts#show', as: :special_post
  get 'news/archives/:month/:year' => 'posts#archives', as: :archives
  post '/news/comments' => 'comments#create'

  post '/admin/time_online' => 'time_onlines#set_time'
  post '/comment_load' => 'posts#comments_show_all'

  #=============================================== User chat =================
  post 'chat/new' => 'live_chats#new'
  post 'chat/create' => 'live_chats#create', as: :user_chat_create
  post 'chat/close' => 'live_chats#close'
  post 'chat/send' => 'live_chats#msg_send', as: :user_chat
  #=============================================== Admin chat ================
  post '/pusher/auth'
  post '/admin_chat/send_msg'
  post '/admin_chat/close'
  post '/admin_chat/go_offline', as: :admin_go_offline
  #===========================================================================

  get 'projects/:id' => 'projects#show', as: :project_load

  root to: 'home#index'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id             :integer          not null, primary key
#  title          :string(255)
#  description    :text
#  admin_user_id  :integer
#  comments_count :integer          default(0)
#  created_at     :datetime
#  updated_at     :datetime
#  slug           :string(255)
#

class Post < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  acts_as_taggable

  belongs_to :admin_user
  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories
  has_many :comments, dependent: :destroy
  has_one :upload_file, as: :fileable, dependent: :destroy

  accepts_nested_attributes_for :upload_file

  default_scope {order('posts.created_at DESC')}

  validates :title, presence: true, length: {minimum: 3, maximum: 255}
  validates :description, presence: true, length: {minimum: 10}
  validates :admin_user_id, presence: true, numericality: {only_integer: true, greater_than: 0}
  validate  :validates_img_name

  def self.search_posts_based_on_like(search)
    if search
      where('LOWER(title) LIKE LOWER(:word) OR LOWER(description) LIKE LOWER(:word)', word:  "%#{search}%")
    else
      all
    end
  end

  def validates_img_name
    if upload_file.img_name.blank?
      errors.add(:base, "img_name can't be blank")
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :category, only: [:index , :show, :archives]
  before_action :recent_and_popular_posts, only: :show

  def index
    @posts = if !params[:category_name].blank?
               Post.joins(:categories).includes([:tags, :upload_file]).where('categories.name = :category_name', category_name: params[:category_name]).page(params[:page]).per(5)
             elsif !params[:tag_name].blank?
               Post.joins(:tags).includes([:categories, :upload_file]).where('tags.name = :tag_name', tag_name: params[:tag_name]).page(params[:page]).per(5)
             else
               Post.includes([:tags, :categories, :upload_file]).search_posts_based_on_like(params[:search]).page(params[:page]).per(5)
             end
    unless params[:search].blank?
      if params[:search].length > 50
        flash.now[:error] = "#{t('.search_max_error')}"
      elsif !params[:search].nil? && @posts.empty?
        flash.now[:error] = "#{t('.your_search_for')} #{params[:search]} #{t('.returned_no_hits')}"
      else
        flash.now[:notice] = "#{t('.your_search_for')} '#{params[:search]}' results"
        gon.search_text = params[:search]
      end
    end
    respond_to do |format|
      format.html {render :index, layout: 'news'}
      format.rss {render :index, content_type: Mime::XML}
    end
  end

  def archives
    if Date::MONTHNAMES.include? params[:month].to_s.capitalize
      if params[:year].to_i <= DateTime.now.year.to_i
        from_date = DateTime.new(params[:year].to_i, Date::MONTHNAMES.index(params[:month].to_s.capitalize), 1)
        till_date = from_date + 1.month
        @posts = Post.includes([:tags, :categories, :upload_file]).where('created_at >= ? AND created_at < ?', from_date, till_date).page(params[:page]).per(5)
        if @posts.blank?
          flash.now[:error] = "No created posts at: #{from_date.strftime('%B %Y')}"
        else
          flash.now[:notice] = "Posts created at: #{from_date.strftime('%B %Y')}"
        end
        render :index, layout: 'news'
      else
        render 'public/404', layout: false, status: 404
      end
    else
       render 'public/404', layout: false, status: 404
    end
  end

  def show
    @post = Post.includes([:tags, :categories, :upload_file, :comments]).find_by_slug!(params[:id])
    @comments = @post.comments.order('id DESC').limit(3).reverse
    @comments_count = @post.comments.count
    respond_to do |format|
      format.html {render :show, layout: 'news'}
    end
  end

  def comments_show_all
    post = Post.find(params[:id])
    comments = (post.comments.order('created_at DESC').limit(post.comments_count).offset(params[:offset]))
    render json: {comments: comments}
  end

  private
  def category
    @categories = Category.includes(:posts).group('categories.id')
    @tags = Post.tag_counts_on(:tags).order('count DESC').limit(20)
  end

  def recent_and_popular_posts
    @recent_posts = Post.order('created_at DESC').limit(5)
    @popular_posts = Post.order('comments_count DESC').limit(5)
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  include ActsAsTaggableOn::TagsHelper

end

app/views/posts/_sidebar.html.haml
#sidebar
  = link_to posts_path(:rss) do
    = image_tag 'rss.png', width: 50
  %h3 Search
  %form.form-search{action: posts_path}
    %input.search-query.form-control{type: 'text', placeholder: t('.search'), name: 'search'}
    %button
      Search
  %h3 Categories
  %ul
    - @categories.each do |category|
      - category_path = posts_path(category_name: category.name)
      - unless category.posts.blank?
        - if request.fullpath == category_path
          %li.active
            = link_to category.name, category_path
        - else
          %li
            = link_to category.name, category_path
  %h3
    - if @tags.blank?
      = t '.tags_are_not_added'
    - else
      = t '.tags'
  .cloud
    %canvas{width: '200', height: '300', id: 'myCanvas'}
      %div#tagcloud
        - unless @tags.nil?
          - tag_cloud(@tags, %w(cloud-tag1 cloud-tag2 cloud-tag3 cloud-tag4 cloud-tag5)) do |tag, css_class|
            = link_to tag.name , posts_path(tag_name: tag.name), class: css_class
  %h3 Archives
  %ul
    - 5.times do |i|
      %li
        - date = i.to_i.month.ago
        = link_to date.strftime('%B %Y'), archives_path(date.strftime('%B').to_s.downcase, date.year.to_s.downcase)
  %div
    %fieldset{id: 'archives_form'}
      = select_tag :month, options_for_select(Date::MONTHNAMES[1..-1])
      = select_tag :year, options_for_select(Array(2010..DateTime.now.year.to_i))
    %button{id: 'archives_url'}
      Show

app/views/posts/index.html.haml
- @posts.each do |post|
  %h3= post.title
  - unless post.upload_file.blank? || post.upload_file.img_name.blank?
    = image_tag post.upload_file.img_name.url, width: 200
  - else
    = image_tag 'no_image.gif', width: 200
  = link_to "#{pluralize(post.comments_count, t('.comment'))}", "#{special_post_path(post.created_at.strftime('%d-%m-%Y'), post)}#comments"
  %p
    = link_to post.title, special_post_path(post.created_at.strftime('%d-%m-%Y'), post)
  %p
    = truncate_html post.description, length: 1000
    = link_to 'learn more', special_post_path(post.created_at.strftime('%d-%m-%Y'), post)
  %p
    %em
      = post.created_at.strftime('%d %B %H:%M:%S')
    - unless post.categories.empty?
      .categories
        = t '.categories'
        != post.categories.collect{|cat| link_to strip_links(cat.name), posts_path(category_name: cat.name)}.join(', ')
    - unless post.tags.blank?
      .tags
        = t '.tags'
        - post.tags.each do |tag|
          = link_to tag.name, posts_path(tag_name: tag.name), class: 'btn btn-default btn-small'
- if @posts.total_pages > 1
  .pagination-panel
    = paginate @posts

app/views/posts/show.html.haml
.row
  .col-lg-12
    .col-lg-8.posts.main_cont
      .post
        .post_top
          .post_img
            .img
              - unless @post.upload_file.blank? || @post.upload_file.img_name.blank?
                = image_tag @post.upload_file.img_name.url(:thumb), class: @post.id
              - else
                = image_tag 'no_image.gif', class: @post.id
          .post-title
            = @post.title
          .post_date
            = @post.created_at.strftime('%d %B %H:%M:%S')
          %span.comments_count
            = pluralize(@post.comments_count, t('.comment'))
        .post-content
          != @post.description
        - unless @post.categories.empty?
          .categories
            = t '.categories'
            != @post.categories.collect{|cat| link_to strip_links(cat.name), posts_path(category_name: cat.name)}.join(', ')
        - unless @post.tags.empty?
          .tags
            = t '.tags'
            - @post.tags.each do |tag|
              = link_to tag.name, posts_path(tag_name: tag.name), class: 'btn btn-default btn-small'
      .comments_block
        -if @post.comments_count > 3
          #all_comments
            %b= 'Show previous comments'
        #close_comments
          %b= 'Hide previous comments'
        .comments
          %a{name: 'comments'}
          - i = @comments_count - 3
          - @comments.each do |comment|
            %blockquote{id: i}
              - i += 1
              .comment_nickname
                %b.text-primary
                  = comment.nickname
              .comment_description
                = comment.description
              %br
              %small.comment_time
                = time_ago_in_words comment.created_at
                = 'ago'
              %hr
      .comments-form
        = form_for [@post, @comment = Comment.new ], html: {class: 'form-inline'}, remote: true do |f|
          .comment_block
            = t '.new_comment'
            .form-group
              = f.text_field :nickname, class: 'form-control input-small', placeholder: t('.write_nickname')
            .form-group
              = f.text_field :description, class: 'form-control input-small', placeholder: t('.write_comment')
            .form-group#recaptcha
              = recaptcha_tags display: {theme: 'white'}, ajax: true
            .form-group
              = f.submit t('.add_comment'), class: 'btn btn-primary btn-small', id: 'go_comment', data: {disable_with: 'Please wait...'}
      .col-lg-6
        .recent_posts
          %h3
            = t ('.most_recent_post')
          %ul.unstyled
            - @recent_posts.each do |post|
              %li
                = link_to post.title, special_post_path(post.created_at.strftime('%d-%m-%Y'), post)
          %h5
            = t ('.get_more')
          .btn
            = link_to t('.rss_feed'), posts_path(:rss), class: 'btn btn-primary'
      .col-lg-6
        .popular_posts
          %h3
            = t '.most_popular'
          %ul.unstyled
            - @popular_posts.each do |post|
              %li
                = link_to post.title, special_post_path(post.created_at.strftime('%d-%m-%Y'), post)
          %h5
            = t '.ready_help'
          .btn
            = link_to t('.contact_us'), contact_index_path, class: 'btn btn-primary'
    .col-lg-4.sidebar