config/routes.rb
RorTeam::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'

  resources :posts, path: 'news', only: [:index] do
    resources :comments, only: [:new, :create]
  end
  resources :home, only: [:index, :create]
  resources :team, only: [:index, :show]
  resources :company, only: [:index]
  resources :projects, only: [:index]
  resources :jobs, only: [:index, :show, :create]
  resources :contact, only: [:index, :create]
  resources :resume, only: [:new, :create, :show]

  get 'news/:created/:id' => 'posts#show', as: :special_post
  get 'news/archives/:month/:year' => 'posts#archives', as: :archives
  post '/news/comments' => 'comments#create'

  post '/admin/time_online' => 'time_onlines#set_time'
  post '/comment_load' => 'posts#comments_show_all'

  #=============================================== User chat =================
  post 'chat/new' => 'live_chats#new'
  post 'chat/create' => 'live_chats#create', as: :user_chat_create
  post 'chat/close' => 'live_chats#close'
  post 'chat/send' => 'live_chats#msg_send', as: :user_chat
  #=============================================== Admin chat ================
  post '/pusher/auth'
  post '/admin_chat/send_msg'
  post '/admin_chat/close'
  post '/admin_chat/go_offline', as: :admin_go_offline
  #===========================================================================

  get 'projects/:id' => 'projects#show', as: :project_load

  root to: 'home#index'

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index
    @message = Message.new
    @services = Service.includes(:upload_file)
  end

  def create
    @message = Message.new(params[:message])
    if verify_recaptcha(model: @message, message: 'You enter wrong captcha', attribute: :base) && @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, notice: t('.contact_sent_msg'))
    else
      flash.now[:error] = @message.errors.full_messages.join(', ')
      @services = Service.includes(:upload_file)
      render :index
    end
  end

end

app/views/contact/index.html.haml
.col-lg-6
  %h1
    = t '.contact_us'
  .web-form.row
    = form_for @message, url: contact_index_path, html: {class: 'web-form', multipart: true} do |form|
      - if @message.errors.any?
        .ror-team-errors
          %h6
            = pluralize(@message.errors.count, 'error')
            prohibited this message from being sent:
          %ul
            - @message.errors.full_messages.each do |msg|
              %li= msg
      .name.col-lg-12.form-group
        = form.text_field(:name, placeholder: 'Your name*', class: 'form-control')
      .email.col-lg-12.form-group
        = form.email_field(:email, placeholder: 'Your email*', class: 'form-control')
      .phone.col-lg-12.form-group
        = form.telephone_field(:phone, placeholder: 'Your phone', class: 'form-control')
      .text.col-lg-12.form-group
        = form.text_area(:text, placeholder: 'Your message', class: 'form-control' , rows: '5')
      .options.col-lg-12.form-group
        %h3
          What kind of services do you need?
        .icons.row.radio
          - @services.each do |service|
            .col-lg-3.text-center
              %label
                - unless service.upload_file.blank? || service.upload_file.img_name.blank?
                  = image_tag service.upload_file.img_name.url, title: service.name, alt: service.name, height: 100
                - else
                  = image_tag 'no_image.gif', width: 100
                .contact_service
                  = form.radio_button :service_type, service.name
                  = service.name
      .radio.col-lg-12
        %h4
          Im interested in?
        .choose
          %label.col-lg-12
            = form.radio_button :work_type, 'Minimum work project'
            = 'Minimum work project'
          %label.col-lg-12
            = form.radio_button :work_type, 'Work project from the beginning'
            = 'Work project from the beginning'
          %label.col-lg-12
            = form.radio_button :work_type, 'Help with existing project'
            = 'Help with existing project'
          %label.col-lg-12
            = form.radio_button :work_type, 'Technical audit'
            = 'Technical audit'
          %label.col-lg-12
            = form.radio_button :work_type, 'Increase in productivity'
            = 'Increase in productivity'
          %label.col-lg-12
            = form.radio_button :work_type, 'Update to new Rails'
            = 'Update to new Rails'
          %label.col-lg-12
            = form.radio_button :work_type, 'Service'
            = 'Service'
      .form-group.col-lg-12#recaptcha-contact-email
        #recaptcha
          = recaptcha_tags display: {theme: 'white'}, ajax: true
      .submit-form.text-right
        = submit_tag 'Send Message', class: 'btn btn-primary send-email', data: {disable_with: 'Please wait...'}
.col-lg-6
  .row
    .col-lg-9.col-offset-2.form-group
      - if session[:chat_id].blank?
        = render partial: 'contact/new_chat'
      - else
        = render partial: 'contact/chat'

app/views/contact/new.html.haml
.row
  .span6
    %h1
      = t '.contact_us'
    .web-form
      = form_for @message, :url => contact_new_path do |form|
        - if @message.errors.any?
          #error_explanation
            %h5
              = pluralize(@message.errors.count, 'error')
              prohibited this message from being sent:
            %ul
              - @message.errors.full_messages.each do |msg|
                %li= msg
        .name
          = form.text_field(:name, 'placeholder' => 'Your name', 'class' => 'span4')
        .email-phone
          = form.email_field(:email, 'placeholder' => 'Your email', 'class' => 'span2')
          = form.text_field(:phone, 'placeholder' => 'Your phone', 'class' => 'span2')
        .text
          = form.text_area(:text, 'placeholder' => 'Your message', 'class' => 'span4' , 'rows' => '5')
        .options
          %h3
            What kind of services do you need?
          .icons
            .span2
              = form.check_box :service_type1
              = form.label :service_type1, 'Web'
            .span2
              = form.check_box :service_type2
              = form.label :service_type2, 'Mobile'
            .span2
              = form.check_box :service_type3
              = form.label :service_type3, 'Web+Mobile'
        .radios
          %h4
            Im interested in?
          .choose
            = form.radio_button :work_type, '1'
            = form.label :work_type_1, 'Minimum work project'
            = form.radio_button :work_type, '2'
            = form.label :work_type_2, 'Work project from the beginning'
            = form.radio_button :work_type, '3'
            = form.label :work_type_3 do
              Help with existing project
              %br
              Tech. audit
              %br
              Increase in productivity
              %br
              Update to new Rails
              %br
              Service
        .submit-form.text-right
          = submit_tag 'Send Message', :class => 'btn', data: { disable_with: 'Please wait...' }